### ISSUE TITLE
MacOS: Transmission not possible, but microphone works

### ISSUE THREAD

**Issue by flymia** [pierr3/VectorAudio#14] opened 2022-04-25 17:14 UTC
When I try to use the software on a real frequency, other pilots can not hear me on the frequency. I also do not get an indicator, that I'm speaking right now. It seems, that the PTT is not working.

After installation I configured the software (inserted my VATSIM ID, changed to my mic+speaker) and tested my microphone using the microphone option. It seems to be working fine there, but when I try to talk on the frequency, nothing happens. I even tried setting another push-to-talk key.

I also compiled the software by myself on my M1 machine, to test if Rosetta 2 was the problem, but it also seems to be not working when running the ARM version. Running the software form the command line does not display any error messages, etc.

System: M1 Mac Mini
OS: macOS Monterey 12.2.1

**Comment by flymia** [comment] 2022-04-25 20:01
Update: I got it to work, but I had to relaunch multiple times. Still don't know what the error is.

**Comment by pierr3** [comment] 2022-04-25 20:05
It's a weird issue with how macOS handles input monitoring permissions. I don't really get how it's so inconsistent, and there doesn't seem to be a way to forward declare that the app will need to use this permission. 

One potential fix is to only look at joysticks inputs which are global but that means most user will need to map a keyboard key as a joystick input.

Another way would be to rewrite the global hotkey detection code in platform specific way in objective-c for macOS.

Any suggestions welcome :)

**Comment by flymia** [comment] 2022-04-26 20:41
Interesting observation today: When I ran the application directly from the Launchpad, I got the same error. But when I launched it on the command line with the typical `/Applications/VectorAudio.App/Contents/macOS/vectoraudio` it works. Strange.

**Comment by jamieernest** [comment] 2022-06-06 08:15
You have to allow Monitor Keyboard inputs and Microphone use for the Unix Executable in System Prefences (click on Vector Audio, then right click, show package contents, MacOS and then choose vectoraudio)

**Comment by flymia** [comment] 2022-06-07 07:29
@jamieernest I already did that, but it does not seem to work anyway. The issue can be closed, since I seem to be the only one having this problem. It works when I launch it through my terminal (see my comment from 26th April)

**Comment by jamieernest** [comment] 2022-06-22 14:09
So I just updated to Monterey 12.4 and back when I was using Monterey 12.1 it was working fine and now it asked me for microphone permissions and PTT doesnt work again hmm

**Comment by kmoberg** [comment] 2022-08-22 09:59
I'm on 12.5.1, I keep getting asked for mic permission on every single connection and have no PTT working. Tried what others have suggested in this thread to no avail, unfortunately.

**Comment by kmoberg** [comment] 2022-08-28 17:02
> I'm on 12.5.1, I keep getting asked for mic permission on every single connection and have no PTT working. Tried what others have suggested in this thread to no avail, unfortunately.

Replying to myself here. Found a solution in the end - launch the executable from the command line, i.e. `# /Applications/VectorAudio.app/Contents/MacOS/vector_audio` then it captures perfectly fine, but running the .app from Applications does not work at all.

**Comment by jamieernest** [comment] 2022-11-28 18:21
> > I'm on 12.5.1, I keep getting asked for mic permission on every single connection and have no PTT working. Tried what others have suggested in this thread to no avail, unfortunately.
> 
> 
> 
> Replying to myself here. Found a solution in the end - launch the executable from the command line, i.e. `# /Applications/VectorAudio.app/Contents/MacOS/vector_audio` then it captures perfectly fine, but running the .app from Applications does not work at all.

Just tried that on Ventura, works as intended, now I just start VectorAudio using a .sh file, hopefully this gets fixed soon. Either way, thank you Pierre for such a wonderful project!

**Comment by pierr3** [comment] 2022-11-30 03:37
This may have been fixed in the latest [pre-release](https://github.com/pierr3/VectorAudio/releases/tag/v0.3.1-6954f5b), as I code-signed the AppBundle which may help macOS remember the settings. @jamieernest could you give it a try? Thanks!

**Comment by jamieernest** [comment] 2022-11-30 15:12
> This may have been fixed in the latest [pre-release](https://github.com/pierr3/VectorAudio/releases/tag/v0.3.1-6954f5b), as I code-signed the AppBundle which may help macOS remember the settings. @jamieernest could you give it a try? Thanks!

Nice, did a fresh install and now it works, thank you so much!

**Closed** 2022-12-02 01:54 UTC
