### ISSUE TITLE
Freezes in v1.6.1

### ISSUE THREAD

**Issue by maxlk96** [pierr3/VectorAudio#104] opened 2024-01-15 21:05 UTC
Since last update I also get random freezes in middle of pilots transmitting, here are some memory dumps, if they can help!(?)

Too big to upload here, so:
*LINK REMOVED*

Crashes became more and more common this session. so I had to switch to AFV client for the rest of the session.

_Originally posted by @maxlk96 in https://github.com/pierr3/VectorAudio/issues/92#issuecomment-1892720421_

**Comment by pierr3** [comment] 2024-04-15 05:28
Dupe of #101

**Closed by pierr3** 2024-04-15 05:28 UTC
