### ISSUE TITLE
Unable to transmit when connected to an _1_ position

### ISSUE THREAD

**Issue by neilenns** [pierr3/VectorAudio#109] opened 2024-03-29 16:27 UTC
To reproduce:

1. Have someone already connected to a position, e.g. `PDX_TWR`, in CRC
2. Connect to the same position in CRC with a plan to relieve the other controller
3. Activate your session in CRC, you'll be connected as `PDX_1_TWR`
4. Connect in VectorAudio

Result: You'll connect, but your audio will never transmit out to pilots even though the `TX` indicator will light up
Expected result: Audio transmits fine

It appears to be specific to having `_1_` in the callsign. If you wait to connect in CRC until after the other controller disconnects (so you connect as `PDX_TWR`) everything works fine

**Comment by pierr3** [comment] 2024-03-29 16:40
Thank you for the report, it’s not the only report i’ve had on something
similar, I will look into it.

**Comment by neilenns** [comment] 2024-04-06 21:16
> I've had success fixing this by Forcing a refresh of the audio station in VectorAudio.

How do you do that?

**Comment by DhruvK1985** [comment] 2024-04-06 22:07
Click on the box with station name and select “Force refresh”

**Comment by neilenns** [comment] 2024-04-06 22:35
> Click on the box with station name and select “Force refresh”

I had no idea that menu was there. Thanks!

**Comment by neilenns** [comment] 2024-04-11 12:41
The "Force refresh" method unfortunately doesn't work for me. To work around the issue I do this:

1. Connect as a _1 position
2. Wait for the other person to disconnect
3. Right click on the position in vector audio and delete it
4. Re-add the position

**Comment by pierr3** [comment] 2024-04-15 05:30
When this situation occurs, just manually add your station, for example `PDX_TWR` and use that to transmit, everything should work as intended. The only issue is that VectorAudio does not consider _1_ to be a relief callsign, it only looks at double underscores.

**Comment by pierr3** [comment] 2024-04-29 03:23
This was fixed in [TrackAudio](https://github.com/pierr3/TrackAudio), please head over to that repo for this

**Closed by pierr3** 2024-04-29 03:23 UTC
