### ISSUE TITLE
Connecting sometimes thinks your callsign is ATIS

### ISSUE THREAD

**Issue by dhawton** [pierr3/VectorAudio#63] opened 2023-08-12 03:27 UTC
If you get disconnected, reconnecting if you don't close vATIS seems to cause VectorAudio to use that as your callsign.

Reproduction steps:
1) Connect to network using preferred client
2) Load vATIS and connect that to network
3) Connect VectorAudio, callsign will become `xxxx_ATIS` and will not stay connected or seem to figure out the callsign

If you connect VectorAudio then vATIS, but then get disconnected, it can get tedious especially if in high workload situations to go through and disconnect the multiple ATIS connections in vATIS, to then connect VectorAudio, then reconnect vATIS.

**Comment by pierr3** [comment] 2023-08-12 12:31
Good catch, I know what the issue is and will fix.

**Comment by pierr3** [comment] 2023-08-30 15:13
Fixed in 1.4.0!

**Closed by pierr3** 2023-08-30 15:13 UTC
Labels: bug
